export default {
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  CLEAR_EMAIL: 'CLEAR_EMAIL',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  CLEAR_PASSWORD: 'CLEAR_PASSWORD',
  UPDATE_PASSWORDCONFIRM: 'UPDATE_PASSWORDCONFIRM',
  CLEAR_PASSWORDCONFIRM: 'CLEAR_PASSWORDCONFIRM',
  SET_AUTHENTICATED: 'SET_AUTHENTICATED',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  CLEAR_ACCESS_TOKEN: 'CLEAR_ACCESS_TOKEN',
  SET_AUTH_ERROR: 'SET_AUTH_ERROR',
  CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
  SET_ERROR: 'SET_ERROR',
};
