export default {
  SET_CONTRACT_CONN: 'SET_CONTRACT_CONN',
  UPDATE_CHOICE: 'UPDATE_CHOICE',
  ADD_CHOICE: 'ADD_CHOICE',
  UPDATE_CHOICE_VOTES: 'UPDATE_CHOICE_VOTES',
  SUBMIT_CHOICE_SENT: 'SUBMIT_CHOICE_SENT',
  SUBMIT_CHOICE_CLEARED: 'SUBMIT_CHOICE_CLEARED',
  SUBMIT_CHOICE_ERROR: 'SUBMIT_CHOICE_ERROR',
};
